# Generated by Django 3.0.7 on 2020-06-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('1', 'کارخانه'), ('2', 'دفتر مرکزی'), ('3', 'فروشگاه')], default='', max_length=20)),
                ('job_title', models.CharField(choices=[('1', 'اپراتور'), ('2', 'انتظامات'), ('3', 'برنامه نویس'), ('4', 'تحلیلگر کسب و کار'), ('5', 'توسعه دهنده نرم افزار'), ('6', 'توسعه دهنده وب'), ('7', 'تکنسین شبکه'), ('8', 'تکنسین فنی'), ('9', 'خیاط'), ('10', 'دستیار اجرائی مدیر عامل'), ('11', 'رئیس امور فروشگاهها'), ('12', 'رئیس تولید'), ('13', 'سرپرست آزمایشگاه'), ('14', 'طراح لباس'), ('15', 'فروشنده')], default='', max_length=20)),
                ('organization_level', models.CharField(choices=[('1', 'کارشناس'), ('2', 'کارمند'), ('3', 'مدیر'), ('4', 'سرپرست')], default='', max_length=20)),
                ('workplace', models.CharField(max_length=120)),
                ('descriptions', models.TextField()),
                ('skills_required', models.CharField(max_length=120)),
                ('experience', models.CharField(max_length=20)),
                ('education', models.CharField(max_length=120)),
                ('salary', models.CharField(max_length=100)),
                ('release_time', models.CharField(max_length=120)),
                ('show_salary', models.BooleanField(default=False)),
                ('creation_date', models.DateTimeField()),
                ('operation', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], default='InActive', max_length=10)),
            ],
        ),
    ]
