# Generated by Django 3.0.7 on 2020-06-28 10:45

import candidate.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(blank=True, choices=[('IN', 'Intern'), ('NG', 'New grad'), ('CL', 'Career level'), ('SR', 'Senior'), ('PR', 'Principal')], max_length=3, null=True)),
                ('education', models.CharField(choices=[('1', 'دیپلم'), ('2', 'فوق دیپلم'), ('3', 'لیسانس'), ('4', 'کارشناسی ارشد'), ('5', 'دکترا')], default='NEW', max_length=3)),
                ('phone', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=150)),
                ('sex', models.CharField(choices=[('1', 'آقا'), ('2', 'خانم')], default='', max_length=2)),
                ('email', models.CharField(max_length=150)),
                ('skills', models.CharField(choices=[('JA', 'Python'), ('PY', 'Java'), ('HA', 'Haskell'), ('C', 'C'), ('JS', 'Javascript (Node)'), ('PE', 'Perl'), ('PH', 'PHP'), ('CP', 'C++'), ('RA', 'Racket'), ('RU', 'Ruby'), ('SC', 'Scala')], default='', max_length=20)),
                ('skills_offers', models.CharField(max_length=100)),
                ('referrer', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('resume', models.FileField(blank=True, null=True, upload_to=candidate.models.determine_upload_location, validators=[django.core.validators.FileExtensionValidator(['pdf', 'txt', 'doc', 'docx'])])),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
